POST http://localhost:8000/api/articles/
Content-Type: application/json
Authorization: Token 51a9b895185d049257ab3de15383af18f7117325

{
    "title": "New Article",
    "content": "New content",
    "category": "development",
    "tags": [
        "python",
        "django"
    ]
}